### ISSUE TITLE
sounddevice error in RealTimeInference

### ISSUE THREAD

**Issue by ankurdhuriya** [juanmc2005/StreamingSpeakerDiarization#115]
sounddevice.PortAudioError: <exception str() failed>

**Comment by juanmc2005** [comment]
Hi @ankurdhuriya, could you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)? I'm not able to reproduce the error using v0.6.

Also, how did you install portaudio?

**Comment by ankurdhuriya** [comment]
>>> from diart import OnlineSpeakerDiarization
>>> from diart.sources import MicrophoneAudioSource
>>> from diart.inference import RealTimeInference
>>> from diart.sinks import RTTMWriter
>>> pipeline = OnlineSpeakerDiarization()
>>> pipeline.config
<diart.blocks.diarization.PipelineConfig object at 0x16f5909d0>
>>> pipeline.config.sample_rate
16000
>>> pipeline = OnlineSpeakerDiarization()
KeyboardInterrupt
>>> mic = MicrophoneAudioSource(pipeline.config.sample_rate)
||PaMacCore (AUHAL)|| AUHAL component not found.Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ankurdhuriya/opt/miniconda3/envs/diart/lib/python3.8/site-packages/diart/sources.py", line 125, in __init__
    self._mic_stream = sd.InputStream(
  File "/Users/ankurdhuriya/opt/miniconda3/envs/diart/lib/python3.8/site-packages/sounddevice.py", line 1421, in __init__
    _StreamBase.__init__(self, kind='input', wrap_callback='array',
  File "/Users/ankurdhuriya/opt/miniconda3/envs/diart/lib/python3.8/site-packages/sounddevice.py", line 898, in __init__
    _check(_lib.Pa_OpenStream(self._ptr, iparameters, oparameters,
  File "/Users/ankurdhuriya/opt/miniconda3/envs/diart/lib/python3.8/site-packages/sounddevice.py", line 2745, in _check
    raise PortAudioError(errormsg, err, hosterror_info)
sounddevice.PortAudioError: <exception str() failed>
