### ISSUE TITLE
Bug: Error while patching annotation coming from an empty RTTM

### ISSUE THREAD

**Issue by zaouk** [juanmc2005/StreamingSpeakerDiarization#80]
When trying to run `diart` on some audio file that doesn't have a voice activity, I got an `IndexError: list index out of range`.

Traceback:

```
Streaming 01047da6: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 461/461 [02:00<00:00,  3.74it/s]Stream took 0.260 (+/-0.009) seconds/chunk -- based on 461 chunks
Streaming 01047da6: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 461/461 [02:00<00:00,  3.83it/s]
Traceback (most recent call last):
  File "/Users/khaled/anaconda3/envs/diart_custom/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/khaled/anaconda3/envs/diart_custom/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/khaled/Desktop/StreamingSpeakerDiarization/src/diart/stream.py", line 51, in <module>
    run()
  File "/Users/khaled/Desktop/StreamingSpeakerDiarization/src/diart/stream.py", line 47, in run
    RealTimeInference(args.output, do_plot=not args.no_plot)(pipeline, audio_source)
  File "/Users/khaled/Desktop/StreamingSpeakerDiarization/src/diart/inference.py", line 69, in __call__
    source.read()
  File "/Users/khaled/Desktop/StreamingSpeakerDiarization/src/diart/sources.py", line 116, in read
    self.stream.on_completed()
  File "/Users/khaled/anaconda3/envs/diart_custom/lib/python3.8/site-packages/rx/subject/subject.py", line 89, in on_completed
    super().on_completed()
  File "/Users/khaled/anaconda3/envs/diart_custom/lib/python3.8/site-packages/rx/core/observer/observer.py", line 56, in on_completed
    self._on_completed_core()
  File "/Users/khaled/anaconda3/envs/diart_custom/lib/python3.8/site-packages/rx/subject/subject.py", line 97, in _on_completed_core
    observer.on_completed()
  File "/Users/khaled/anaconda3/envs/diart_custom/lib/python3.8/site-packages/rx/core/observer/autodetachobserver.py", line 44, in on_completed
    self._on_completed()
  File "/Users/khaled/anaconda3/envs/diart_custom/lib/python3.8/site-packages/rx/core/operators/do.py", line 63, in _on_completed
    observer.on_completed()
  File "/Users/khaled/anaconda3/envs/diart_custom/lib/python3.8/site-packages/rx/core/observer/autodetachobserver.py", line 44, in on_completed
    self._on_completed()
  File "/Users/khaled/anaconda3/envs/diart_custom/lib/python3.8/site-packages/rx/core/observer/autodetachobserver.py", line 44, in on_completed
    self._on_completed()
  File "/Users/khaled/anaconda3/envs/diart_custom/lib/python3.8/site-packages/rx/core/observer/autodetachobserver.py", line 44, in on_completed
    self._on_completed()
  [Previous line repeated 6 more times]
  File "/Users/khaled/anaconda3/envs/diart_custom/lib/python3.8/site-packages/rx/core/operators/do.py", line 70, in _on_completed
    observer.on_completed()
  File "/Users/khaled/anaconda3/envs/diart_custom/lib/python3.8/site-packages/rx/core/observer/autodetachobserver.py", line 44, in on_completed
    self._on_completed()
  File "/Users/khaled/anaconda3/envs/diart_custom/lib/python3.8/site-packages/rx/core/operators/do.py", line 70, in _on_completed
    observer.on_completed()
  File "/Users/khaled/anaconda3/envs/diart_custom/lib/python3.8/site-packages/rx/core/observer/autodetachobserver.py", line 44, in on_completed
    self._on_completed()
  File "/Users/khaled/Desktop/StreamingSpeakerDiarization/src/diart/sinks.py", line 44, in on_completed
    self.patch_rttm()
  File "/Users/khaled/Desktop/StreamingSpeakerDiarization/src/diart/sinks.py", line 27, in patch_rttm
    annotation = list(load_rttm(self.path).values())[0]
IndexError: list index out of range
```

**Comment by juanmc2005** [comment]
Fixed in #81
